django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from qanda.forms import CustomAuhthenticationForm
from qanda.views import SignUpView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(form_class=CustomAuhthenticationForm),
         name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('', include('qanda.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

django/qanda/urls.py
from django.urls import path, re_path
from qanda import views

app_name = 'qanda'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ask/', views.CreateQuestion.as_view(), name='ask_question'),
    path('question/<int:question_id>/vote/',
         views.QuestionVoteCreate.as_view(), name='question_vote_create'),
    path('question/<int:question_id>/vote/<int:pk>/',
         views.QuestionVoteUpdate.as_view(), name='question_vote_update'),
    path('question/<int:question_id>/answer/',
         views.AnswerCreate.as_view(), name='answer-create'),
    path('question/<int:pk>/<str:title>/',
         views.QuestionDetail.as_view(), name='question_detail'),
    path('answer/<int:answer_id>/vote/',
         views.AnswerVoteCreate.as_view(), name='answer_vote_create'),
    path('answer/<int:answer_id>/vote/<int:pk>/',
         views.AnswerVoteUpdate.as_view(), name='answer_vote_update'),
    path('answer/<int:pk>/', views.UpdateAnswerAcceptanceView.as_view(),
         name='update_accepted_answer'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('users/<str:username>/',
         views.UserDetail.as_view(), name='user-detail'),
    path('q/search', views.SearchView.as_view(), name='question_search'),
    path('question/<int:pk>/subscribe',
         views.QuestionSubscriptionCreate.as_view(),
         name='question_subscription_create'),
    path('question/<int:pk>/subscribe/delete',
         views.QuestionSubscriptionDelete.as_view(),
         name='question_subscription_delete'),
]

django/qanda/views.py
from django.contrib.auth import get_user_model as User
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from qanda.forms import (AnswerAcceptanceForm, AnswerForm, AnswerVoteForm,
                         CustomUserCreationForm, QuestionForm,
                         QuestionVoteForm, QuestionSubscriptionForm)
from qanda.mixins import CacheVaryOnCookieMixin
from qanda.models import (Answer, AnswerVote, Profile, Question, QuestionVote,
                          Tag, QuestionSubscription)
from qanda.service.elasticsearch import search_for_questions
from qanda.tokens import account_activation_token


class CreateQuestion(LoginRequiredMixin, CreateView):
    template_name = 'qanda/ask_question.html'
    form_class = QuestionForm

    success_url = '/'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            question = form.save()
            for tag in form.custom_tags:
                try:
                    tag_model = Tag.objects.get(name=tag)
                except Tag.DoesNotExist:
                    tag_model = Tag.objects.create(name=tag)
                question.tags.add(tag_model)
                tag_model.save()

            question.save()
            # Save and redirect as usual
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                title=form.cleaned_data['title'],
                body=form.cleaned_data['body'])
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetail(DetailView):
    queryset = Question.objects.all_with_relations_and_score()

    def get_vote_data(self, model, obj, url_id, create_url, update_url):
        vote = model.objects.get_vote_or_unsaved_blank_vote(
            obj_instance=obj,
            vote_user=self.request.user)
        if vote.id:
            vote_form_url = reverse(update_url, kwargs={
                url_id: obj.id, 'pk': vote.id})
        else:
            vote_form_url = reverse(create_url, kwargs={
                url_id: obj.id})

        return {'instance': vote, 'url': vote_form_url}

    def get_context_data(self, **kwargs):
        self.object.viewed += 1
        self.object.save()
        ctx = super(QuestionDetail, self).get_context_data(**kwargs)
        ctx['answers'] = []
        answers = Answer.objects.all_with_score() \
            .filter(question=self.object.id)

        for ans in answers:
            answer_dict = {}
            answer_dict['info'] = ans
            ctx['answers'].append(answer_dict)

        if self.object.can_accept_answers(self.request.user):
            ctx['accept_form'] = \
                AnswerAcceptanceForm(initial={'accepted': True})
            ctx['reject_form'] = \
                AnswerAcceptanceForm(initial={'accepted': False})

        if self.request.user.is_authenticated:
            if (QuestionSubscription.objects.is_subscribed(
                    user=self.request.user, question=self.object)):
                ctx['subscribed'] = True
            else:
                ctx['subscribed'] = False

            vote_data = self.get_vote_data(
                QuestionVote, self.object, 'question_id',
                'qanda:question_vote_create',
                'qanda:question_vote_update')
            vote_form = QuestionVoteForm(instance=vote_data['instance'])
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_data['url']

            i = 0
            for ans in answers:
                answer_dict = {}
                ans_vote_data = self.get_vote_data(
                    AnswerVote, ans, 'answer_id', 'qanda:answer_vote_create',
                    'qanda:answer_vote_update')

                answer_dict['vote_form'] = AnswerVoteForm(
                    instance=ans_vote_data['instance'])
                answer_dict['vote_url'] = ans_vote_data['url']
                ctx['answers'][i].update(answer_dict)
                i += 1

            ctx['answer_form'] = AnswerForm()
            ctx['answer_form_url'] = reverse('qanda:answer-create', kwargs={
                'question_id': self.object.id})

        return ctx


class QuestionVoteCreate(LoginRequiredMixin, CreateView):
    form_class = QuestionVoteForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'question': self.kwargs['question_id'],
        }

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class QuestionVoteUpdate(LoginRequiredMixin, UpdateView):
    form_class = QuestionVoteForm
    queryset = QuestionVote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        if vote.user != self.request.user:
            raise PermissionDenied('Cannot change another user\'s vote')
        return vote

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class AnswerCreate(LoginRequiredMixin, CreateView):
    form_class = AnswerForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'question': self.kwargs['question_id'],
        }

    def get_success_url(self):
        return self.object.question.get_absolute_url()


class AnswerVoteCreate(LoginRequiredMixin, CreateView):
    form_class = AnswerVoteForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'answer': self.kwargs['answer_id'],
        }

    def get_success_url(self):
        return self.object.answer.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class AnswerVoteUpdate(LoginRequiredMixin, UpdateView):
    form_class = AnswerVoteForm
    queryset = AnswerVote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        if vote.user != self.request.user:
            raise PermissionDenied('Cannot change another user\'s vote')
        return vote

    def get_success_url(self):
        return self.object.answer.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()


class HomePageView(CacheVaryOnCookieMixin, ListView):
    template_name = 'qanda/homepage.html'
    model = Question
    paginate_by = 10
    timeout = 60*2

    def get_context_data(self, **kwargs):
        ctx = super(HomePageView, self).get_context_data(**kwargs)
        ctx['last_answers'] = Answer.objects.all() \
            .order_by('-created')[:5]
        ctx['top_users'] = Profile.objects.all_with_user_score() \
            .order_by('-score')[:5]
        ctx['questions'] = ctx['object_list']
        return ctx

    def get_queryset(self):
        sort_by = self.request.GET.get('sort', None)
        qs = Question.objects.all_with_answer_score()
        if (sort_by == 'answered'):
            qs = qs.order_by('-ans_score')
        elif (sort_by != 'newest'):
            qs = qs.order_by("-score")
        return qs


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('qanda:homepage')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Send activation email
        current_site = get_current_site(self.request)
        subject = 'Activate your OffByOneAccount'
        message = render_to_string('email/account_activation.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        user.email_user(subject, message)
        return render(self.request, 'qanda/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('qanda:home')
    else:
        return render(request, 'qanda/account_activation_invalid.html')


class UserDetail(CacheVaryOnCookieMixin, DetailView):
    model = User()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = 'qanda/user_detail.html'

    def get_context_data(self, **kwargs):

django/qanda/templates/qanda/common/list_answers.html
{% load markup_tags %}

{% for answer in answers %}
        <div class="columns" id="{% if answer.info.accepted %}accepted{% endif %}">
          <div class="column is-1">
            <p class="has-text-centered">{{ answer.info.score }}</p>
            {% if user.is_authenticated and user != answer.info.user %}
            <form method="post" action="{{ answer.vote_url }}">
              {% csrf_token %}
              {{ answer.vote_form.as_p }}
              <input type="submit" class="button is-link" value="Vote">
            </form>
            {% endif %}
          </div>
          <div class="column is-11">
            {{ answer.info.body|apply_markup:"markdown" | linebreaks}}
            {% if answer.info.accepted and reject_form %}
            <br>
            <form method="post" action="{% url "qanda:update_accepted_answer" pk=answer.info.pk %}">
              {% csrf_token %}
              {{reject_form}}
              <input class="button is-danger is-pulled-right" type="submit" value="Reject answer">
            </form>
            {% elif accept_form %}
            <br>
            <form method="post" action="{% url "qanda:update_accepted_answer" pk=answer.info.pk %}">
              {% csrf_token %}
              {{accept_form}}
              <input class="button is-link is-pulled-right" type="submit" value="Accept answer">
            </form>
            {% endif %}
            <br>
            <br>
            <div class="answer-data" style="margin-top: 0.5em">
              <p class="has-text-right"><strong>Answered: </strong> {{ answer.info.created | timesince }} ago by
                <strong><a href="{% url 'qanda:user-detail' username=answer.info.user.username %}">{{answer.info.user}}</a></strong></p>
            </div>
          </div>
        </div>
        <hr>
        {% endfor %}

django/qanda/templates/qanda/common/list_questions.html
<div class="question">
  {% for question in questions %}
  <div class="columns" style="margin-bottom: 0;">
    <div class=" column is-2">
      <ul class="question-stats">
        <li>
          <p class="has-text-centered">{{question.score}}</p>
          <p class="is-size-7">Votes</p>
        </li>
        <li>
          <p class="has-text-centered">{{question.answer_set.all|length}}</p>
          <p class="is-size-7">Answers</p>
        </li>
        <li>
          <p class="has-text-centered">{{question.viewed}}</p>
          <p class="is-size-7">Views</p>
        </li>
      </ul>
    </div>
    <div class="column is-10"  style="padding-bottom: 0">
      <a href="{% url 'qanda:question_detail' pk=question.id title=question.title_as_hyphen %}" class="question-title is-size-5 has-text-info">{{question.title}}</a>
        
     <div class="extra-info">
      <div class="tags" style="margin-bottom: 0.5em">
       {% for tag in question.tags.all %}
        <span class="tag is-dark is-small">{{tag.name}}</span>
        {% endfor %}
      </div>
        <p class="has-text-grey-light">Asked {{question.created|timesince}} ago by <strong><a href="{% url 'qanda:user-detail' username=question.user %}">{{question.user}}</a></strong></p>
     </div>
    </div>
  </div>
  <hr style="height: 1px; margin-top: 0;">
  {% endfor %}
</div>

django/qanda/templates/qanda/common/post_answer.html
{% if user.is_authenticated %}
<form action="{{ answer_form_url }}" method="post">
  {% csrf_token %}
  <h2 class="title is-size-4" id="answer">Your Answer</h2>
  {{ answer_form.body }}
  <p><strong>Tip: </strong>You can use markdown here.</p>
  <div class="options">
    <button type="submit" name="action" value="SAVE" class="button is-link">Answer</button>
  </div>
</form>
{% else %}
<p class="has-text-centered">You need to be logged in to post an answer. You can log in <a href="#"
    class="has-text-link">Here</a>.</p>
{% endif %}