django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from qanda.forms import CustomAuhthenticationForm
from qanda.views import SignUpView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(form_class=CustomAuhthenticationForm),
         name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('', include('qanda.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

django/qanda/urls.py
from django.urls import path, re_path
from qanda import views

app_name = 'qanda'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ask/', views.CreateQuestion.as_view(), name='ask_question'),
    path('question/<int:question_id>/vote/',
         views.QuestionVoteCreate.as_view(), name='question_vote_create'),
    path('question/<int:question_id>/vote/<int:pk>/',
         views.QuestionVoteUpdate.as_view(), name='question_vote_update'),
    path('question/<int:question_id>/answer/',
         views.AnswerCreate.as_view(), name='answer-create'),
    path('question/<int:pk>/<str:title>/',
         views.QuestionDetail.as_view(), name='question_detail'),
    path('answer/<int:answer_id>/vote/',
         views.AnswerVoteCreate.as_view(), name='answer_vote_create'),
    path('answer/<int:answer_id>/vote/<int:pk>/',
         views.AnswerVoteUpdate.as_view(), name='answer_vote_update'),
    path('answer/<int:pk>/', views.UpdateAnswerAcceptanceView.as_view(),
         name='update_accepted_answer'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('users/<str:username>/',
         views.UserDetail.as_view(), name='user-detail'),
    path('q/search', views.SearchView.as_view(), name='question_search'),
    path('question/<int:pk>/subscribe',
         views.QuestionSubscriptionCreate.as_view(),
         name='question_subscription_create'),
    path('question/<int:pk>/subscribe/delete',
         views.QuestionSubscriptionDelete.as_view(),
         name='question_subscription_delete'),
]

django/qanda/views.py
from django.contrib.auth import get_user_model as User
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from qanda.forms import (AnswerAcceptanceForm, AnswerForm, AnswerVoteForm,
                         CustomUserCreationForm, QuestionForm,
                         QuestionVoteForm, QuestionSubscriptionForm)
from qanda.mixins import CacheVaryOnCookieMixin
from qanda.models import (Answer, AnswerVote, Profile, Question, QuestionVote,
                          Tag, QuestionSubscription)
from qanda.service.elasticsearch import search_for_questions
from qanda.tokens import account_activation_token


class CreateQuestion(LoginRequiredMixin, CreateView):
    template_name = 'qanda/ask_question.html'
    form_class = QuestionForm

    success_url = '/'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            question = form.save()
            for tag in form.custom_tags:
                try:
                    tag_model = Tag.objects.get(name=tag)
                except Tag.DoesNotExist:
                    tag_model = Tag.objects.create(name=tag)
                question.tags.add(tag_model)
                tag_model.save()

            question.save()
            # Save and redirect as usual
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                title=form.cleaned_data['title'],
                body=form.cleaned_data['body'])
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetail(DetailView):
    queryset = Question.objects.all_with_relations_and_score()

    def get_vote_data(self, model, obj, url_id, create_url, update_url):
        vote = model.objects.get_vote_or_unsaved_blank_vote(
            obj_instance=obj,
            vote_user=self.request.user)
        if vote.id:
            vote_form_url = reverse(update_url, kwargs={
                url_id: obj.id, 'pk': vote.id})
        else:
            vote_form_url = reverse(create_url, kwargs={
                url_id: obj.id})

        return {'instance': vote, 'url': vote_form_url}

    def get_context_data(self, **kwargs):
        self.object.viewed += 1
        self.object.save()
        ctx = super(QuestionDetail, self).get_context_data(**kwargs)
        ctx['answers'] = []
        answers = Answer.objects.all_with_score() \
            .filter(question=self.object.id)

        for ans in answers:
            answer_dict = {}
            answer_dict['info'] = ans
            ctx['answers'].append(answer_dict)

        if self.object.can_accept_answers(self.request.user):
            ctx['accept_form'] = \
                AnswerAcceptanceForm(initial={'accepted': True})
            ctx['reject_form'] = \
                AnswerAcceptanceForm(initial={'accepted': False})

        if self.request.user.is_authenticated:
            if (QuestionSubscription.objects.is_subscribed(
                    user=self.request.user, question=self.object)):
                ctx['subscribed'] = True
            else:
                ctx['subscribed'] = False

            vote_data = self.get_vote_data(
                QuestionVote, self.object, 'question_id',
                'qanda:question_vote_create',
                'qanda:question_vote_update')
            vote_form = QuestionVoteForm(instance=vote_data['instance'])
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_data['url']

            i = 0
            for ans in answers:
                answer_dict = {}
                ans_vote_data = self.get_vote_data(
                    AnswerVote, ans, 'answer_id', 'qanda:answer_vote_create',
                    'qanda:answer_vote_update')

                answer_dict['vote_form'] = AnswerVoteForm(
                    instance=ans_vote_data['instance'])
                answer_dict['vote_url'] = ans_vote_data['url']
                ctx['answers'][i].update(answer_dict)
                i += 1

            ctx['answer_form'] = AnswerForm()
            ctx['answer_form_url'] = reverse('qanda:answer-create', kwargs={
                'question_id': self.object.id})

        return ctx


class QuestionVoteCreate(LoginRequiredMixin, CreateView):
    form_class = QuestionVoteForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'question': self.kwargs['question_id'],
        }

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class QuestionVoteUpdate(LoginRequiredMixin, UpdateView):
    form_class = QuestionVoteForm
    queryset = QuestionVote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        if vote.user != self.request.user:
            raise PermissionDenied('Cannot change another user\'s vote')
        return vote

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class AnswerCreate(LoginRequiredMixin, CreateView):
    form_class = AnswerForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'question': self.kwargs['question_id'],
        }

    def get_success_url(self):
        return self.object.question.get_absolute_url()


class AnswerVoteCreate(LoginRequiredMixin, CreateView):
    form_class = AnswerVoteForm

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'answer': self.kwargs['answer_id'],
        }

    def get_success_url(self):
        return self.object.answer.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class AnswerVoteUpdate(LoginRequiredMixin, UpdateView):
    form_class = AnswerVoteForm
    queryset = AnswerVote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        if vote.user != self.request.user:
            raise PermissionDenied('Cannot change another user\'s vote')
        return vote

    def get_success_url(self):
        return self.object.answer.get_absolute_url()

    def render_to_response(self, context, **response_kwargs):
        return redirect(to=self.get_success_url())


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()


class HomePageView(CacheVaryOnCookieMixin, ListView):
    template_name = 'qanda/homepage.html'
    model = Question
    paginate_by = 10
    timeout = 60*2

    def get_context_data(self, **kwargs):
        ctx = super(HomePageView, self).get_context_data(**kwargs)
        ctx['last_answers'] = Answer.objects.all() \
            .order_by('-created')[:5]
        ctx['top_users'] = Profile.objects.all_with_user_score() \
            .order_by('-score')[:5]
        ctx['questions'] = ctx['object_list']
        return ctx

    def get_queryset(self):
        sort_by = self.request.GET.get('sort', None)
        qs = Question.objects.all_with_answer_score()
        if (sort_by == 'answered'):
            qs = qs.order_by('-ans_score')
        elif (sort_by != 'newest'):
            qs = qs.order_by("-score")
        return qs


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('qanda:homepage')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Send activation email
        current_site = get_current_site(self.request)
        subject = 'Activate your OffByOneAccount'
        message = render_to_string('email/account_activation.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        user.email_user(subject, message)
        return render(self.request, 'qanda/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('qanda:home')
    else:
        return render(request, 'qanda/account_activation_invalid.html')


class UserDetail(CacheVaryOnCookieMixin, DetailView):
    model = User()
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = 'qanda/user_detail.html'

    def get_context_data(self, **kwargs):

django/qanda/templates/qanda/account_activation_invalid.html
{% extends 'core/base.html' %}

{% block title %}Account activation invalid URL | {{block.super}} {% endblock title %}

{% block body %}
<h1 class="title has-text-centered">Invalid confirmation link</h1>
<p class="has-text-centered">The confirmation link was invalid, possibly because it has already been used.</p>

<br>
<div class="has-text-centered">
  <a class="button is-link" href="{% url 'qanda:home' %}">Go home</a> 
</div>
{% endblock body %}

django/qanda/templates/qanda/account_activation_sent.html
{% extends 'core/base.html' %}

{% block title %}Account created | {{block.super}} {% endblock title %}

{% block body %}
<h1 class="title has-text-centered">Account sucessfully created</h1>
<p class="has-text-centered">Please confirm your email address to complete the registration.</p>

<br>
<div class="has-text-centered">
  <a class="button is-link" href="{% url 'qanda:home' %}">Go home</a> 
</div>
{% endblock body %}

django/qanda/templates/qanda/ask_question.html
{% extends 'core/base.html' %}
{% load markup_tags %}

{% block title %}Ask your question{% endblock title %}

{% block body %}
{% if preview  %}
<div class="content">
  <article class="message is-info">
    <div class="message-header">
      <p>Question preview</p>
    </div>
    <div class="message-body">
      <h2>{{ preview.title }}</h2>
      {{ preview.body|apply_markup:"markdown" }}
    </div>
  </article>
</div>
{% endif %}

<h1 class="title">Ask your question</h2>
  <p class="has-text-centered">Remember to abide by the community guidelines and try to make you question as clear
    and informative as possible, you can use the markdown syntax to provide better and more specific formatting </p>
  <hr>

<form method="post">
  {% csrf_token %}

  <h2 class="title">Title</h2>
  {{ form.title }}
  {% if form.title.errors %}
  <p class="has-text-danger">{{form.title.errors}}</p>
  {% endif %}
  <h2 class="title" style="margin-top: 1.2em">Body</h2>
  {{ form.body }}
  <h2 class="title" style="margin-top: 1.2em">Tags (separated by commas)</h2>
  {{ form.custom_tags }}
  {% if form.custom_tags.errors %}
  <div class="has-text-danger">{{form.custom_tags.errors}}</div>
  {% endif %}

  <div class="options">
    <button type="submit" name="action" value="PREVIEW" class="button is-link">Preview</button>
    <button type="submit" name="action" value="SAVE" class="button is-link">Publish</button>
  </div>
</form>
{% endblock body %}

django/qanda/templates/qanda/homepage.html
{% extends 'core/base.html' %}
{% load cache %}

{% block title %}{{block.super}}{% endblock title %}

{% block body %}
<div class="top-bar">
  <h1 class="title" style="margin-bottom: 0">Top Questions</h1>

  <div class="tabs is-toggle">
    <ul>
      <li class="{% if not 'sort' in request.GET %} is-active {% endif %}">
        <a href="{% url 'qanda:home' %}">
          <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Top&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        </a>
      </li>
      <li class="{% if 'sort' in request.GET and request.GET.sort == 'newest'%} is-active {% endif %}">
        <a href="{% url 'qanda:home' %}?sort=newest">
          <span>Newest</span>
        </a>
      </li>
      <li class="{% if 'sort' in request.GET and request.GET.sort == 'answered'%} is-active {% endif %}">
        <a href="{% url 'qanda:home' %}?sort=answered">
          <span>Answered</span>
        </a>
      </li>
    </ul>
  </div>
</div>
<hr>
<div class="columns">
  <div class="column is-9">
    {% include "qanda/common/list_questions.html" %}
    {% if is_paginated %}
    <nav class="pagination" role="navigation" aria-label="pagination">
      {% if page_obj.has_previous %}
      <a class="pagination-previous"
        href="?page={{ page_obj.previous_page_number }}{% if request.GET.sort %}&sort={{request.GET.sort}}{% endif %}">Previous</a>
      {% else %}
      <a class="pagination-previous" disabled>Previous</a>
      {% endif %}
      {% if page_obj.has_next %}
      <a class="pagination-next"
        href="?page={{ page_obj.next_page_number }}{% if request.GET.sort %}&sort={{request.GET.sort}}{% endif %} ">Next
        page</a>
      {% else %}
      <a class="pagination-previous" disabled>Next Page</a>
      {% endif %}
      <ul class="pagination-list">
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <a class="pagination-link is-current">{{i}}</a>
        </li>
        {% else %}
        <li>
          <a class="pagination-link"
            href="?page={{ i }}{% if request.GET.sort %}&sort={{request.GET.sort}}{% endif %}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
      </ul>
    </nav>
    {% endif %}
  </div>
  <div class="column is-3">
    <article class="message">
      <div class="message-header">
        <p>Latest Answers</p>
      </div>
      <div class="message-body">
        {% cache 300 latest_answers %}
        {% for answer in last_answers %}
        <p class="is-size-6">{{answer.score}} <a class="has-text-info"
            href="{% url 'qanda:question_detail' pk=answer.question.id title=answer.question.title_as_hyphen %}">{{ answer.question.title }}</a>
          <span class="is-size-7"> by </span><strong class="is-size-7">{{answer.user}}</strong></p>
        <hr style="margin: 0.2em 0; height: 1px">
        {% endfor %}
        {% endcache %}
      </div>
    </article>
    <h2 class="title is-size-4" style="margin-bottom: 0.5em">Top Contributors</h2>
    {% for user in top_users %}
    <p class="is-size-5">{{user.score}} {{user}}</p>
    {% endfor %}
  </div>
</div>

{% endblock body %}

django/qanda/templates/qanda/question_detail.html
{% extends 'core/base.html' %}
{% load markup_tags %}

{% block title %} {{ question.title }} {% endblock title %}

{% block body %}

<p class="title">{{ question.title }}</p>
<hr>
<div class="columns">
  <div class="column is-1">
    <p class="has-text-centered  is-size-4">{{ question.score }}</p>
    {% if vote_form %}
    <form method="post" action="{{ vote_form_url }}">
      {% csrf_token %}
      {{ vote_form.as_p }}
      <input type="submit" class="button is-link" value="Vote">
    </form>
    {% endif %}
  </div>
  <div class="column is-8 has-text-justified">
    {{ question.body|apply_markup:"markdown" | linebreaks}}
    <br>
    {% for tag in question.tags.all %}
    <span class="tag is-dark is-medium">{{tag}}</span>
    {% endfor %}
    <br><br>
    <p class="is-size-4" style="margin-bottom: 0.3em">{{answers | length}} Answer{{answers|pluralize}}</p>
    <hr>

    {% include "qanda/common/list_answers.html" %}

    {% include "qanda/common/post_answer.html" %}

  </div>

  <div class="column is-3">
    <p><strong>Asked: </strong>{{question.created | timesince}} ago</p>
    <p><strong>Viewed: </strong>{{question.viewed}} time{{question.viewed|pluralize}}</p>
    <p><strong>By: </strong><a href="{% url 'qanda:user-detail' username=question.user.username%}">{{question.user}}</a>
    </p>
    <br>
    <article class="message">
      <div class="message-header">
        <p>Placeholder temporal sidebar</p>
      </div>
      <div class="message-body">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus
        quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam,
        et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec
        sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec
        dui urna, vehicula et sem eget, facilisis sodales sem.
      </div>
    </article>
    {% if user.is_authenticated %}
    <form action="{% if subscribed %}
      {% url 'qanda:question_subscription_delete' pk=question.pk %}
    {% else %}
      {% url 'qanda:question_subscription_create' pk=question.pk %}
    {% endif %}" method="post">
      {% csrf_token %}
      <input type="checkbox" name="subscribe" onChange="this.form.submit()" {% if subscribed %}checked{% endif %}>
      <label for="subscribe" class="tooltip"
        data-tooltip="You will receive email updates whenever a new answer is posted">Subscribe to question <i
          class="fas fa-question-circle"></i></label>
    </form>
    {% endif %}
  </div>
</div>

{% endblock body %}

django/qanda/templates/qanda/search.html
{% extends 'core/base.html' %}

{% block title %} Post containing '{{query}}' | {{block.super}} {% endblock title %}

{% block body %}
  {% if query %}
    {% if questions|length > 0 %}
      <h1 class="title is-size-4">{{questions|length}} result{{questions|pluralize}} found for '{{query}}'</h1>
      <hr>
      {% include 'qanda/common/list_questions.html' %}
    {% else %}
      <p class="subtitle is-size-4 has-text-centered">No answers found, you could try with another search or <a class="is-link" href="{% url 'qanda:ask_question' %}">post a question</a>.</p>
    {% endif %}
  {% endif %}
{% endblock body %}

django/qanda/templates/qanda/user_detail.html
{% extends 'core/base.html' %}

{% block title %} {{user.username}} | {{block.super}}{% endblock title %}

{% block body %}
<div class="tabs">
  <ul>
    <li class="{% if not 'tab' in request.GET %} is-active {% endif %}"><a
        href="{% url 'qanda:user-detail' username=user.username %}">Summary</a></li>
    <li class="{% if 'tab' in request.GET and request.GET.tab == 'answers'%} is-active {% endif %}"><a
        href="{% url 'qanda:user-detail' username=user.username %}?tab=answers">Answers</a></li>
    <li class="{% if 'tab' in request.GET and request.GET.tab == 'questions'%} is-active {% endif %}"><a
        href="{% url 'qanda:user-detail' username=user.username %}?tab=questions">Questions</a></li>
  </ul>
</div>

<div class="columns">
  <div class="column is-9">

    {% if 'tab' in request.GET and request.GET.tab == 'answers' %}
    <h2 class="title is-size-4">{{user.answer_set.all|length}} Answers</h2>
    <hr>
    {% for answer in answers  %}
    <p class="subtitle" style="margin-left: 1.5em">{{answer.score}} <a
        href="{% url 'qanda:question_detail' pk=answer.question.pk title=answer.question.title %}">{{answer.question.title}}</a>
    </p>
    {% endfor %}
    {% elif 'tab' in request.GET and request.GET.tab == 'questions' %}
    <h2 class="title is-size-4">{{user.question_set.all|length}} Questions</h2>
    <hr>
    {% include "qanda/common/list_questions.html" %}

    {% else %}

    <h1 class="title" style="margin-bottom: 1em">Top answers</h1>
    {% for answer in answers %}
    <p class="subtitle" style="margin-left: 1.5em">{{answer.score}} <a
        href="{% url 'qanda:question_detail' pk=answer.question.pk title=answer.question.title %}">{{answer.question.title}}</a>
    </p>
    {% endfor %}
    {% if user.answer_set.all|length > 5 %}
    <p class="subtitle" style="margin-left: 1.5em"><a href="{% url 'qanda:user-detail' username=user.username %}?tab=answers">View more → </a></p>
    {% endif %}
    <br>

    <h1 class="title" style="margin-bottom: 1em">Top Questions</h1>
    {% for question in questions %}
    <p class="subtitle" style="margin-left: 1.5em">{{question.score}} <a
        href="{% url 'qanda:question_detail' pk=question.pk title=question.title %}">{{question.title}}</a>
    </p>
    {% endfor %}
    
    {% if user.question_set.all|length > 5 %}
    <p class="subtitle" style="margin-left: 1.5em"><a href="{% url 'qanda:user-detail' username=user.username %}?tab=questions">View more → </a></p>
    {% endif %}

    {% endif %}

  </div>
  <div class="column is-3">
    <div class="user-info">
      <p class="subtitle is-size-4">{{user.first_name}} {{user.last_name}} ({{user}}) </p>
      <h r>
        <p class="subtitle is-size-6">{{user.answer_set.all|length}} answer{{user.answer_set.all|length|pluralize}}</p>
        <p class="subtitle is-size-6">{{user.question_set.all|length}}
          question{{user.question_set.all|length|pluralize}}</p>
        <p class="subtitle is-size-6"><i class="fas fa-history"></i> Member for {{user.date_joined|timesince}}</p>
        <p class="subtitle is-size-6"><i class="far fa-clock"></i> Last seen {{user.last_login|timesince}} ago</p>
    </div>
  </div>
</div>

{% endblock body %}