django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from qanda.forms import CustomAuhthenticationForm
from qanda.views import SignUpView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(form_class=CustomAuhthenticationForm),
         name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('', include('qanda.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

django/qanda/urls.py
from django.urls import path, re_path
from qanda import views

app_name = 'qanda'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('ask/', views.CreateQuestion.as_view(), name='ask_question'),
    path('question/<int:question_id>/vote/',
         views.QuestionVoteCreate.as_view(), name='question_vote_create'),
    path('question/<int:question_id>/vote/<int:pk>/',
         views.QuestionVoteUpdate.as_view(), name='question_vote_update'),
    path('question/<int:question_id>/answer/',
         views.AnswerCreate.as_view(), name='answer-create'),
    path('question/<int:pk>/<str:title>/',
         views.QuestionDetail.as_view(), name='question_detail'),
    path('answer/<int:answer_id>/vote/',
         views.AnswerVoteCreate.as_view(), name='answer_vote_create'),
    path('answer/<int:answer_id>/vote/<int:pk>/',
         views.AnswerVoteUpdate.as_view(), name='answer_vote_update'),
    path('answer/<int:pk>/', views.UpdateAnswerAcceptanceView.as_view(),
         name='update_accepted_answer'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('users/<str:username>/',
         views.UserDetail.as_view(), name='user-detail'),
    path('q/search', views.SearchView.as_view(), name='question_search'),
    path('question/<int:pk>/subscribe',
         views.QuestionSubscriptionCreate.as_view(),
         name='question_subscription_create'),
    path('question/<int:pk>/subscribe/delete',
         views.QuestionSubscriptionDelete.as_view(),
         name='question_subscription_delete'),
]

django/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}OffByOne{% endblock title %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-extensions@6.2.7/bulma-tooltip/dist/css/bulma-tooltip.min.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <script defer src="{% static 'js/main.js' %}"></script>
</head>

<body>
  <div id="content-wrap">
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'qanda:home' %}">
          <img src="{% static 'assets/logo-text-white.svg' %}" width="125" height="35">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarItems">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu is-active">
        <div class="navbar-start">
          <div class="navbar-item">
            <form action="{% url 'qanda:question_search' %}" method="get">
              <div class="field has-addons">
                <div class="control">
                  <input class="input" id="search-box" name="q" type="text" placeholder="Search" required>
                </div>
                <div class="control">
                  <button class="button is-link" type="submit">Search</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div id="navbarItems" class="navbar-menu">
        <div class="navbar-end">
          {% if user.is_authenticated %}
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              {{user}}
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item" href="{% url 'qanda:user-detail' username=user.username %}">
                Profile
              </a>
              <a class="navbar-item" href="{% url 'logout' %}">
                Logout
              </a>
            </div>
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-link" href="{% url 'qanda:ask_question' %}">Ask</a>
              </div>
            </div>


            {% else %}
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-link" href="{% url 'register' %}">Register</a>
                <a class="button" href="{% url 'login' %}">Login</a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
    </nav>

    <section class="section">
      <div class="container">
        {% block body %}{% endblock body %}
      </div>
    </section>
  </div>
  <footer class="footer" style="background-color: #363636">
    <div class="content" id="content-footer">
      <ul class="footer-list">
        <hr>
        <li class="footer-list-item list-title">OffByOne</li>
        <li class="footer-list-item"><a href="#">Questions</a></li>
        <li class="footer-list-item"><a href="#">Users</a></li>
        <li class="footer-list-item"><a href="#">Help</a></li>
      </ul>
      <ul class="footer-list">
        <hr>
        <li class="footer-list-item list-title">Latests Posts</li>
        <li class="footer-list-item"><a href="#">Latest server improvements</a></li>
        <li class="footer-list-item"><a href="#">How to ask a good question</a></li>
      </ul>

      <ul class="footer-list">
        <hr>
        <li class="footer-list-item list-title">About Us</li>
        <li class="footer-list-item"><a href="#">Privacy Policy</a></li>
        <li class="footer-list-item"><a href="#">Privacy Policy</a></li>
        <li class="footer-list-item"><a href="#">Terms of service</a></li>
      </ul>

      <div id="f-right-side">
        <ul>
          <li clas="footer-list-item"><a href="#">Blog</a></li>
          <li clas="footer-list-item"><a href="#">Facebook</a></li>
          <li clas="footer-list-item"><a href="#">Twitter</a></li>
        </ul>
        <p>© Copyright 2019 OffbyOne Inc.</p>
      </div>

    </div>
  </footer>
</body>

</html>